services:
  postgres:
    image: postgres:15-alpine
    container_name: cv_builder_postgres
    environment:
      POSTGRES_DB: cv_builder
      POSTGRES_USER: cv_user
      POSTGRES_PASSWORD: cv_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cv_user -d cv_builder"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
